package org.example.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2015-01-11T20:19:09.342+05:30
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://www.example.org/hello/", name = "HelloPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HelloPort {

    @WebResult(name = "sayHelloResponse", targetNamespace = "http://www.example.org/hello/", partName = "NewPart")
    @WebMethod(action = "http://www.example.org/hello/sayHelloOperation")
    public java.lang.String sayHelloOperation(
        @WebParam(partName = "NewPart", name = "sayHello", targetNamespace = "http://www.example.org/hello/")
        java.lang.String newPart
    );
}
